### ISSUE TITLE
API endpoint outdated?

### ISSUE THREAD

**Issue by ninayujiri** [clement-joye/react-websitecarbon-badge#4]
Website carbon API is called using the `/b` endpoint (`const res = await fetch("https://api.websitecarbon.com/b?url=" + url)`)

However, in the [API documentation](https://api.websitecarbon.com/#site-endpoint), it's stated that the `/site` endpoint should be used with the URL to get back site data. The API always returns a 503 `{
  "error": "Service temporarily unavailable."
}` when using `WebsiteCarbonBadge` as is.

Am I missing something?

**Comment by clement-joye** [comment]
Hi @ninayujiri,
Thanks for your issue.
It seems like the team behind website carbon is currently updating their api to a new version with new endpoints.

So `https://api.websitecarbon.com/site?url=www.google.com` now returns something like this:
```{
  "url": "https://www.google.com/",
  "green": true,
  "bytes": 176943,
  "cleanerThan": 0.96,
  "statistics": {
    "adjustedBytes": 133591.965,
    "energy": 0.00010077794236131013,
    "co2": {
      "grid": {
        "grams": 0.04454385052369908,
        "litres": 0.024775289661281424
      },
      "renewable": {
        "grams": 0.03861810751285405,
        "litres": 0.02147939139864942
      }
    }
  },
  "timestamp": 1674765544
}
```

However the endpoint I use in this npm package still seem to return proper response.
So `https://api.websitecarbon.com/b?url=www.google.com` still returns something like:
```
{
  "c": 0.18,
  "p": 82,
  "url": "https://www.google.com/"
}
```

Although I didn't know that there was some changes in the api, I will try to update this package with a new version that uses the new api version.

**Comment by ninayujiri** [comment]
@clement-joye Makes sense! I figured it was something to do with their "work in progress" note on the API docs so I closed the ticket. Seems like that endpoint has limited access for the moment. I've reached out to the WebsiteCarbon team directly but will use the static `co2` and `percentage` props for now. Thanks!

**Comment by clement-joye** [comment]
Sounds good. Thanks for the note!
