### ISSUE TITLE
Issue while fetching 

### ISSUE THREAD

**Issue by Federiko9811** [clement-joye/react-websitecarbon-badge#7]
I installed the component correctly, but if I put the url of my site it fails to get the data from the api, while if I use for example www.google.com it succeeds correctly. Also if I make the call to the api _https://api.websitecarbon.com/b?url=mydomain_ from my browser it succeeds correctly in getting the data. I think there is some problem with cors.

**Comment by clement-joye** [comment]
Hi Federiko, did you find out the solution to our problem ?
